name: nexora-postgres

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexora-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-nexora_dev}
      POSTGRES_USER: ${POSTGRES_USER:-nexora_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nexora_pass_dev_123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexora_net

volumes:
  postgres_data:
    name: nexora_postgres_data

networks:
  nexora_net:
    external: true
